/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Asus' at '16/10/17 08:49 PM' with Gradle 2.14.1
 *
 * @author Asus, @date 16/10/17 08:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
